"""
PoB の UI 関連 Lua ファイルから label を抽出して一括日本語化するスクリプト。

translate_config.py を汎用化したもの。CalcsTab / CalcSections / Build /
BuildDisplayStats / ItemsTab / SkillsTab / TreeTab / ConfigOptions など
全UIファイルからラベル抽出する。

出力: ui_translations.lua (ja.lua にマージするための Lua テーブル断片)
"""
from __future__ import annotations

import re
from pathlib import Path

# 翻訳対象のソースファイル
SOURCE_FILES = [
    "src/Modules/ConfigOptions.lua",
    "src/Modules/BuildDisplayStats.lua",
    "src/Modules/CalcSections.lua",
    "src/Modules/Calcs.lua",
    "src/Modules/Build.lua",
    "src/Classes/CalcsTab.lua",
    "src/Classes/ItemsTab.lua",
    "src/Classes/SkillsTab.lua",
    "src/Classes/TreeTab.lua",
    "src/Classes/ConfigTab.lua",
    "src/Classes/PartyTab.lua",
    "src/Classes/CompareTab.lua",
    "src/Classes/ImportTab.lua",
    "src/Classes/NotesTab.lua",
]

# ============================================================
# ゲーム用語辞書 (英→日)
# ============================================================
TERMS: dict[str, str] = {
    # 略語 (長い順に登録 = 短い置換に上書きされない)
    "MH Inc. Att. Speed": "MH 攻撃速度増加",
    "MH More Att. Speed": "MH 攻撃速度上昇",
    "MH Att. per second": "MH 毎秒攻撃",
    "MH Inc. Crit Chance": "MH クリ率増加",
    "MH Crit Chance": "MH クリ率",
    "MH Crit Multiplier": "MH クリ倍率",
    "MH Crit Effect Mod": "MH クリ効果補正",
    "MH Total Increased": "MH 総増加率",
    "MH Total More": "MH 総上昇率",
    "MH Eff. DPS Mod": "MH 実効DPS補正",
    "MH Hit Damage": "MH ヒットダメージ",
    "MH Average Hit": "MH 平均ヒット",
    "MH Accuracy": "MH 命中",
    "MH Chance to Hit": "MH 命中率",
    "MH Stun Threshold": "MH 気絶閾値",
    "MH Stun Duration": "MH 気絶時間",
    "Enemy Ail. Thresh.": "敵 状態異常閾値",
    "MS While Casting": "詠唱中の移動速度",
    "Inc. Quiver Effect": "クイバー効果増加",
    "Inc. Item Quantity": "アイテム数量増加",
    "Inc. Item Rarity": "アイテムレアリティ増加",

    # ダメージタイプ
    "Lightning": "雷",
    "Cold": "冷気",
    "Fire": "炎",
    "Chaos": "混沌",
    "Physical": "物理",
    "Elemental": "属性",
    "Energy Shield": "エナジーシールド",
    "Mana": "マナ",
    "Life": "ライフ",
    "Spirit": "スピリット",
    "Rage": "レイジ",
    "Soul": "ソウル",

    # よく出る単語
    "Total Base": "総基本",
    "Total Increased": "総増加率",
    "Total More": "総上昇率",
    "Base from Gear": "装備からの基本",
    "Base from Armours": "アーマーからの基本",
    "Global Base": "全体基本",
    "Inc. from Tree": "ツリーから増加",
    "Reserved": "予約済み",
    "Unreserved": "未予約",
    "Recovery": "回復",
    "Recharge Rate": "リチャージレート",
    "Recharge Delay": "リチャージ遅延",
    "Phys. Dmg. Reduct": "物理ダメージ軽減",
    "Phys. Dmg. Reduction": "物理ダメージ軽減",
    "Phys Dmg Reduct": "物理ダメージ軽減",
    "Damage Reduction": "ダメージ軽減",
    "Damage Avoidance": "ダメージ回避",
    "Damage Taken": "被ダメージ",
    "Damaging Hits": "ダメージヒット",
    "Hit taken": "被ヒット",
    "Hit taken Mult.": "被ヒット倍率",
    "Hits before death": "死亡までのヒット数",
    "Time before death": "死亡までの時間",
    "Mitigated hits": "軽減ヒット",
    "Mitigated": "軽減",
    "Unmitigated %": "未軽減%",
    "Enemy miss chance": "敵のミス確率",
    "Maximum Hit Taken": "最大被ヒット",
    "Maximum Hit": "最大ヒット",
    "Effective \"Health\" Pool": "実効「ヘルス」プール",
    "Effective Health Pool": "実効ヘルスプール",
    "Recoup and Hit Taken Over Time": "回収と継続被ヒット",
    "Dots and Build Degens": "DoTとビルド継続ダメージ",
    "Enemy Degens": "敵継続ダメージ",
    "DoT taken": "被DoT",
    "Total Pool": "総プール",
    "Effective DoT Pool": "実効DoTプール",
    "Block": "ブロック",
    "Taken From Block": "ブロックからの被害",
    "Dodge": "回避",
    "Dodge Chance": "回避率",
    "Spell Ddg. Chance": "呪文回避率",
    "Spell Dodge Chance": "呪文回避率",
    "Deflection": "受け流し",
    "Deflect Effect": "受け流し効果",
    "Deflect": "受け流し",
    "Eva. as Deflection": "回避→受け流し変換",
    "Arm. as Deflection": "アーマー→受け流し変換",
    "Inc. Effect": "効果増加",
    "Inc. Duration": "持続時間増加",
    "Inc. Charges Gain": "チャージ獲得増加",
    "Inc. Charges Used": "チャージ消費増加",
    "% to not Consume": "消費しない確率%",
    "Charge on crit %": "クリ時チャージ獲得%",
    "Charges/s": "チャージ/秒",
    "Utility Flasks": "ユーティリティフラスコ",
    "Life Flasks": "ライフフラスコ",
    "Mana Flasks": "マナフラスコ",
    "Flasks": "フラスコ",
    "Charms": "チャーム",
    "Charges": "チャージ",
    "Movement Speed": "移動速度",
    "Light Radius Mod": "光半径補正",
    "Light Radius": "光半径",
    "Curse Effect on You": "受ける呪い効果",
    "Curse Effect": "呪い効果",
    "Exposure Effect": "エクスポージャー効果",
    "Wither Effect": "枯死効果",
    "Weap. Swap Speed": "武器持ち替え速度",
    "Weapon Swap Speed": "武器持ち替え速度",
    "Stun Threshold": "気絶閾値",
    "Stun Chance": "気絶確率",
    "Stun Duration": "気絶時間",
    "Block Stun Duration": "ブロック気絶時間",
    "Other Defences": "その他防御",
    "Other Avoidance": "その他回避",
    "Other Ailment Defences": "その他状態異常防御",
    "Ailment Defences": "状態異常防御",
    "Other Effects": "その他効果",

    # Skill Hit Damage 関連
    "Skill Hit Damage": "スキルヒットダメージ",
    "Hit Damage": "ヒットダメージ",
    "Skill DPS": "スキルDPS",
    "Added Min": "最小追加",
    "Added Max": "最大追加",
    "Attack/Cast Rate": "攻撃/詠唱レート",
    "Attack Rate": "攻撃レート",
    "Cast Rate": "詠唱レート",
    "Attack time": "攻撃時間",
    "Skill type-specific Stats": "スキル種別固有ステータス",
    "Curse Limit": "呪い上限",
    "Area of Effect Mod": "範囲効果補正",
    "Area of Effect": "範囲",
    "Weapon Range": "武器射程",
    "Strike Targets": "ストライク対象",
    "Accuracy": "命中",
    "Crits": "クリティカル",
    "Crit": "クリ",
    "Non-Damaging Ailments": "非ダメージ状態異常",
    "Damaging Ailments": "ダメージ状態異常",
    "Ailments": "状態異常",
    "Ailment": "状態異常",
    "Stun Buildup": "気絶蓄積",
    "Stun": "気絶",
    "Surrounded Radius": "包囲半径",
    "Chance to Blind": "盲目確率",
    "Chance to Daze": "目眩確率",
    "Chance to Hit": "命中率",
    "Chance to": "確率",
    "Stat Set": "ステータスセット",
    "View Skill Details": "スキル詳細を見る",
    "Socket Group": "ソケットグループ",
    "Active Skill": "アクティブスキル",
    "Calculation Mode": "計算モード",
    "Effective DPS": "実効DPS",
    "Aura and Buff Skills": "オーラ・バフスキル",
    "Combat Buffs": "戦闘バフ",
    "Curses and Debuffs": "呪い・デバフ",
    "Curses": "呪い",
    "Debuffs": "デバフ",
    "Buffs": "バフ",
    "Buff": "バフ",
    "All Types": "全タイプ",

    # 属性系
    "Attributes": "属性",
    "Str. Required": "必要筋力",
    "Dex. Required": "必要敏捷",
    "Int. Required": "必要知性",
    "Gem Req Mod": "ジェム必要値補正",
    "Item Req Mod": "アイテム必要値補正",
    "Weapon Req Mod": "武器必要値補正",
    "Strength": "筋力",
    "Dexterity": "敏捷",
    "Intelligence": "知性",
    "Strength Required": "必要筋力",
    "Dexterity Required": "必要敏捷",
    "Intelligence Required": "必要知性",

    # 抵抗
    "Resists": "耐性",
    "Resistance": "耐性",
    "Fire Resist": "炎耐性",
    "Cold Resist": "冷気耐性",
    "Lightning Resist": "雷耐性",
    "Chaos Resist": "混沌耐性",
    "Phys. Damage Reduction": "物理ダメージ軽減",

    # アーマー・回避
    "Armour": "アーマー",
    "Evasion": "回避",
    "Evasion Rating": "回避レーティング",

    # その他防御関連
    "Eva. as Deflection": "回避→受け流し",
    "Arm. as Deflection": "アーマー→受け流し",

    # 状態異常
    "Frozen": "凍結",
    "Chilled": "冷却",
    "Brittle": "脆性",
    "Burning": "炎上",
    "Ignited": "発火",
    "Scorched": "灼熱",
    "Shocked": "感電",
    "Sapped": "弱体",
    "Bleeding": "出血",
    "Poisoned": "毒",
    "Blinded": "盲目",
    "Dazed": "目眩",
    "Maimed": "切傷",
    "Pinned": "拘束",
    "Intimidated": "威圧",
    "Crushed": "粉砕",
    "Unnerved": "動揺",
    "Stunned": "気絶",
    "Cursed": "呪い",
    "Fortified": "強化",
    "Onslaught": "猛攻",
    "Adrenaline": "アドレナリン",
    "Channelling": "チャネリング",
    "Sprinting": "全力疾走",
    "Leeching": "吸収",
    "Sacrificing": "犠牲",
    "Elusive": "回避",
    "Focused": "集中",
    "Unbound": "解放",
    "Insane": "発狂",

    # チャージ・スタック
    "Power Charge": "パワーチャージ",
    "Frenzy Charge": "フレンジーチャージ",
    "Endurance Charge": "エンデュランスチャージ",
    "Inspiration Charge": "インスピレーションチャージ",
    "Siphoning Charge": "サイフォニングチャージ",
    "Blitz Charge": "ブリッツチャージ",
    "Blood Charge": "ブラッドチャージ",
    "Challenger Charge": "チャレンジャーチャージ",
    "Spirit Charge": "スピリットチャージ",
    "Charges": "チャージ",
    "Charge": "チャージ",
    "Stacks": "スタック",
    "Stack": "スタック",

    # 敵関連
    "the enemy": "敵",
    "enemy": "敵",
    "Enemy": "敵",
    "Boss": "ボス",
    "Allies": "味方",
    "Minions": "ミニオン",
    "Minion": "ミニオン",
    "Totems": "トーテム",
    "Totem": "トーテム",

    # スキル系
    "Skill": "スキル",
    "Spell": "呪文",
    "Attack": "攻撃",
    "Critical": "クリティカル",
    "Hits": "ヒット",
    "Hit": "ヒット",
    "Cast": "詠唱",
    "Trigger": "トリガー",
    "Aura": "オーラ",
    "Curse": "呪い",
    "Banner": "バナー",
    "Brand": "ブランド",
    "Trap": "トラップ",
    "Mine": "マイン",
    "Warcry": "戦吼",

    # その他
    "Damage": "ダメージ",
    "Penetration": "貫通",
    "Pen.": "貫通",
    "Multiplier": "倍率",
    "Chance": "確率",
    "Rating": "レーティング",
    "Reduction": "軽減",
    "Speed": "速度",
    "Duration": "持続時間",
    "Cooldown": "クールダウン",
    "Reload": "リロード",
    "Distance": "距離",
    "Nearby": "近くの",
    "nearby": "近くの",
    "Active": "アクティブ",
    "active": "アクティブ",
    "Number": "数",
    "Effect": "効果",
    "Bonus": "ボーナス",
    "Always": "常時",
    "always": "常時",
    "Full": "満タン",
    "Low": "低い",
    "moving": "移動中",
    "Maximum": "最大",
    "maximum": "最大",
    "Minimum": "最小",
    "minimum": "最小",
    "average": "平均",
    "Average": "平均",
    "Current": "現在の",
    "current": "現在の",
    "Recently": "最近",
    "recently": "最近",
    "Total": "総計",
    "Mod": "補正",
    "Inc.": "増加",
    "Increased": "増加",
    "More": "上昇",

    # ビルド管理
    "Current build": "現在のビルド",
    "Unnamed build": "無名ビルド",
    "Are you sure": "本当に",
    "Player modifiers": "プレイヤー補正",
    "Enemy modifiers": "敵補正",
}

# 完全一致 (パターンマッチで綺麗にいかないもの)
EXACT: dict[str, str] = {
    # CalcsTab セクションヘッダ
    "View Skill Details:": "スキル詳細を見る:",
    "View Skill Details": "スキル詳細を見る",
    "Socket Group:": "ソケットグループ:",
    "Active Skill:": "アクティブスキル:",
    "Stat Set:": "ステータスセット:",
    "Calculation Mode:": "計算モード:",
    "Effective DPS": "実効DPS",
    "Aura and Buff Skills:": "オーラ・バフスキル:",
    "Combat Buffs:": "戦闘バフ:",
    "Curses and Debuffs:": "呪い・デバフ:",
    "Skill Hit Damage:": "スキルヒットダメージ:",
    "All Types:": "全タイプ:",
    "Physical:": "物理:",
    "Lightning:": "雷:",
    "Cold:": "冷気:",
    "Fire:": "炎:",
    "Chaos:": "混沌:",
    "Added Min:": "最小追加:",
    "Added Max:": "最大追加:",
    "Attack/Cast Rate:": "攻撃/詠唱レート:",
    "Crits:": "クリティカル:",
    "Skill type-specific Stats:": "スキル種別固有ステータス:",
    "Accuracy:": "命中:",
    "Non-Damaging Ailments:": "非ダメージ状態異常:",
    "Other Effects:": "その他効果:",
    "Damage Taken:": "被ダメージ:",
    "Damaging Hits:": "ダメージヒット:",
    'Effective "Health" Pool:': "実効「ヘルス」プール:",
    'Effective "Health" Pool': "実効「ヘルス」プール",
    "Maximum Hit Taken:": "最大被ヒット:",
    "Recoup and Hit Taken Over Time:": "回収と継続被ヒット:",
    "Dots and Build Degens:": "DoTとビルド継続ダメージ:",
    "Enemy Degens:": "敵継続ダメージ:",
    "Curse Limit:": "呪い上限:",
    "Area of Effect Mod:": "範囲効果補正:",
    "Weapon Range:": "武器射程:",
    "Strike Targets:": "ストライク対象:",
    "Enemy Ail. Thresh.:": "敵 状態異常閾値:",
    "Stun Buildup:": "気絶蓄積:",
    "Surrounded Radius:": "包囲半径:",
    "Chance to Blind:": "盲目確率:",
    "Chance to Daze:": "目眩確率:",
    "Inc. Quiver Effect:": "クイバー効果増加:",
    "Inc. Item Quantity:": "アイテム数量増加:",
    "Inc. Item Rarity:": "アイテムレアリティ増加:",
    "MS While Casting:": "詠唱中の移動速度:",
    "Total Pool:": "総プール:",
    "Effective DoT Pool:": "実効DoTプール:",
    "DoT taken:": "被DoT:",
    "Hit taken:": "被ヒット:",
    "Hit taken Mult.:": "被ヒット倍率:",
    "Hits before death:": "死亡までのヒット数:",
    "Time before death:": "死亡までの時間:",
    "Unmitigated %:": "未軽減%:",
    "Mitigated hits:": "軽減ヒット:",
    "Enemy miss chance:": "敵のミス確率:",
    "Total:": "総計:",
    "Maximum Hit Taken:": "最大被ヒット:",

    # Right sidebar 単純ラベル
    "Attributes:": "属性:",
    "Resists:": "耐性:",
    "Fire Resist:": "炎耐性:",
    "Cold Resist:": "冷気耐性:",
    "Lightning Resist:": "雷耐性:",
    "Chaos Resist:": "混沌耐性:",
    "Life:": "ライフ:",
    "Mana:": "マナ:",
    "Spirit:": "スピリット:",
    "Energy Shield": "エナジーシールド",
    "Energy Shield:": "エナジーシールド:",
    "Block:": "ブロック:",
    "Dodge:": "回避:",
    "Deflection:": "受け流し:",
    "Flasks:": "フラスコ:",
    "Charges:": "チャージ:",
    "Charms:": "チャーム:",
    "Stun Duration:": "気絶時間:",
    "Other Defences:": "その他防御:",
    "Other Avoidance:": "その他回避:",
    "Other Ailment Defences:": "その他状態異常防御:",
    "Damage Avoidance:": "ダメージ回避:",
    "Utility Flasks:": "ユーティリティフラスコ:",
    "Life Flasks:": "ライフフラスコ:",
    "Mana Flasks:": "マナフラスコ:",
    "Rage:": "レイジ:",

    # Base from / Inc. from / Total から始まる行
    "Base from Gear:": "装備からの基本:",
    "Base from Armours:": "アーマーからの基本:",
    "Global Base:": "全体基本:",
    "Inc. from Tree:": "ツリーから増加:",
    "Total Base:": "総基本:",
    "Total Increased:": "総増加率:",
    "Total More:": "総上昇率:",
    "Reserved:": "予約済み:",
    "Unreserved:": "未予約:",
    "Recovery:": "回復:",
    "Recharge Rate:": "リチャージレート:",
    "Recharge Delay:": "リチャージ遅延:",
    "Phys. Dmg. Reduct:": "物理ダメージ軽減:",
    "Phys Dmg Reduct:": "物理ダメージ軽減:",

    # その他属性ラベル
    "Str. Required:": "必要筋力:",
    "Dex. Required:": "必要敏捷:",
    "Int. Required:": "必要知性:",
    "Gem Req Mod:": "ジェム必要値補正:",
    "Item Req Mod:": "アイテム必要値補正:",
    "Weapon Req Mod:": "武器必要値補正:",

    # Movement / Other Defences
    "Movement Speed:": "移動速度:",
    "Light Radius Mod:": "光半径補正:",
    "Curse Effect on You:": "受ける呪い効果:",
    "Exposure Effect:": "エクスポージャー効果:",
    "Wither Effect:": "枯死効果:",
    "Weap. Swap Speed:": "武器持ち替え速度:",

    # Stun
    "Stun Threshold:": "気絶閾値:",
    "Stun Chance:": "気絶確率:",
    "Block Stun Duration:": "ブロック気絶時間:",

    # Dodge / Block
    "Dodge Chance:": "回避率:",
    "Spell Ddg. Chance:": "呪文回避率:",
    "Taken From Block:": "ブロックからの被害:",
    "Eva. as Deflection:": "回避→受け流し変換:",
    "Arm. as Deflection:": "アーマー→受け流し変換:",
    "Deflect Effect:": "受け流し効果:",

    # Flask sub-labels
    "Inc. Effect:": "効果増加:",
    "Inc. Duration:": "持続時間増加:",
    "Inc. Charges Gain:": "チャージ獲得増加:",
    "Inc. Charges Used:": "チャージ消費増加:",
    "% to not Consume:": "消費しない確率%:",
    "Charge on crit %:": "クリ時チャージ獲得%:",
    "Charges/s:": "チャージ/秒:",

    # Build top bar
    "Current build:": "現在のビルド:",
    "Unnamed build": "無名ビルド",

    # CalcSections detail row labels (no colon - they get colon at render time)
    "Player modifiers": "プレイヤー補正",
    "Enemy modifiers": "敵補正",
    "Skill base": "スキル基本",
    "Total mod": "総補正",
    "Total damage": "総ダメージ",

    # ConfigOptions / 既存追加分
    "Hide Ineligible Configurations": "無関係な設定を隠す",
    "Show All Configurations": "全設定を表示",

    # =============== 追加翻訳 (untranslated.txt から非固有名詞を抽出) ===============
    # 装備スロット
    "Helmet": "ヘルメット",
    "Helmet:": "ヘルメット:",
    "Gloves": "手袋",
    "Gloves:": "手袋:",
    "Boots": "ブーツ",
    "Boots:": "ブーツ:",
    "Belt": "ベルト",
    "Belt:": "ベルト:",
    "Amulet": "アミュレット",
    "Amulet:": "アミュレット:",
    "Ring 1": "リング 1",
    "Ring 1:": "リング 1:",
    "Ring 2": "リング 2",
    "Ring 2:": "リング 2:",
    "Ring 3": "リング 3",
    "Ring 3:": "リング 3:",
    "Weapon 1": "武器 1",
    "Weapon 1:": "武器 1:",
    "Weapon 2": "武器 2",
    "Weapon 2:": "武器 2:",
    "Weapon 1 (Swap)": "武器 1 (持替)",
    "Weapon 1 (Swap):": "武器 1 (持替):",
    "Weapon 2 (Swap)": "武器 2 (持替)",
    "Weapon 2 (Swap):": "武器 2 (持替):",
    "Main Hand": "メインハンド",
    "Main Hand:": "メインハンド:",
    "Off Hand": "オフハンド",
    "Off Hand:": "オフハンド:",
    "Main hand modifiers": "メインハンド補正",
    "Main hand modifiers:": "メインハンド補正:",
    "Off hand modifiers": "オフハンド補正",
    "Off hand modifiers:": "オフハンド補正:",

    # 共通操作
    "Add": "追加",
    "Save": "保存",
    "Cancel": "キャンセル",
    "Close": "閉じる",
    "Done": "完了",
    "Done:": "完了:",
    "Reset": "リセット",
    "Search": "検索",
    "Copy": "コピー",
    "Create": "作成",
    "Convert": "変換",
    "Import": "取込",
    "Allocate": "配置",
    "Override": "上書き",
    "Override:": "上書き:",
    "Share": "共有",
    "Share:": "共有:",
    "Default": "既定",
    "Default:": "既定:",
    "Custom": "カスタム",
    "Custom:": "カスタム:",
    "Manual": "手動",
    "Manual:": "手動:",
    "Auto": "自動",
    "None": "なし",
    "None:": "なし:",
    "Any": "任意",
    "Any:": "任意:",
    "All": "全て",
    "All:": "全て:",
    "Max": "最大",
    "Max:": "最大:",
    "Prefix": "接頭辞",
    "Prefix:": "接頭辞:",
    "Suffix": "接尾辞",
    "Suffix:": "接尾辞:",
    "Sort by ": "並び順 ",
    "Sort by :": "並び順 :",
    "Spendable": "使用可能",
    "Spendable:": "使用可能:",
    "Don't Save": "保存しない",
    "Don't disable items": "アイテムを無効化しない",
    "Don't disable items:": "アイテムを無効化しない:",
    "Unbuffed": "バフ無し",
    "Unbuffed:": "バフ無し:",
    "In Combat": "戦闘中",
    "In Combat:": "戦闘中:",
    "Corrupted": "コラプト済",
    "Corrupted:": "コラプト済:",
    "Not Corrupted": "コラプト無し",
    "Not Corrupted:": "コラプト無し:",
    "Match Character Level": "キャラレベルに合わせる",
    "Match Character Level:": "キャラレベルに合わせる:",
    "Hide Color Codes": "カラーコードを隠す",
    "Hide Color Codes:": "カラーコードを隠す:",
    "Show Color Codes": "カラーコードを表示",
    "Show Color Codes:": "カラーコードを表示:",
    "Beast Library": "ビースト一覧",
    "Beast Library:": "ビースト一覧:",
    "Spectre Library": "霊体一覧",
    "Spectre Library:": "霊体一覧:",
    "Spectre Ally": "霊体仲間",
    "Spectre Ally:": "霊体仲間:",
    "Import Tree": "ツリーを取込",
    "Import from Folder": "フォルダから取込",
    "Shrink with PoEURL": "PoEURLで短縮",
    "Shrinking...": "短縮中...",
    "Shrinking...:": "短縮中...:",
    "Creating link...": "リンク作成中...",
    "Creating link...:": "リンク作成中...:",
    "Resolving PoEURL link...": "PoEURLリンク解決中...",
    "Resolving PoEURL link...:": "PoEURLリンク解決中...:",
    "Copy Trade URL": "トレードURLをコピー",
    "Copy Trade URL:": "トレードURLをコピー:",
    "Copy Next Trade URL": "次のトレードURLをコピー",
    "Copy Next Trade URL:": "次のトレードURLをコピー:",
    "Copy + Convert": "コピー＋変換",
    "Copy Config from Compare Build": "比較ビルドから設定をコピー",
    "Socket #": "ソケット番号",
    "Socket #:": "ソケット番号:",
    "Gem Level": "ジェムレベル",
    "Gem Level:": "ジェムレベル:",
    "+1 to Gem Level": "ジェムレベル+1",
    "+1 to Gem Level:": "ジェムレベル+1:",
    "-1 to Gem Level": "ジェムレベル-1",
    "-1 to Gem Level:": "ジェムレベル-1:",
    "PoE2": "PoE2",
    "PoE2:": "PoE2:",
    "Lineage": "系譜",
    "Lineage:": "系譜:",
    "Non-Lineage": "系譜外",
    "Non-Lineage:": "系譜外:",

    # 状態系
    "Bleed": "出血",
    "Bleed:": "出血:",
    "Ignite": "発火",
    "Ignite:": "発火:",
    "Poison": "毒",
    "Poison:": "毒:",
    "Decay": "腐敗",
    "Decay:": "腐敗:",
    "Impale": "串刺し",
    "Impale:": "串刺し:",
    "Caustic Ground": "腐食地形",
    "Caustic Ground:": "腐食地形:",
    "Degens": "継続ダメージ",
    "Degens:": "継続ダメージ:",
    "Recoup": "回収",
    "Recoup:": "回収:",
    "Power": "パワー",
    "Power:": "パワー:",
    "Endurance": "エンデュランス",
    "Endurance:": "エンデュランス:",
    "Frenzy": "フレンジー",
    "Frenzy:": "フレンジー:",
    "Guard": "ガード",
    "Guard:": "ガード:",
    "Essence": "エッセンス",
    "Essence:": "エッセンス:",
    "Aegis": "イージス",
    "Aegis:": "イージス:",

    # 計算系・統計ラベル
    "Combined DPS": "合計DPS",
    "Combined DPS:": "合計DPS:",
    "DoT DPS": "DoT DPS",
    "DoT DPS:": "DoT DPS:",
    "Bleed DPS": "出血DPS",
    "Bleed DPS:": "出血DPS:",
    "Ignite DPS": "発火DPS",
    "Ignite DPS:": "発火DPS:",
    "Poison DPS": "毒DPS",
    "Poison DPS:": "毒DPS:",
    "Decay DPS": "腐敗DPS",
    "Decay DPS:": "腐敗DPS:",
    "Impale DPS": "串刺しDPS",
    "Impale DPS:": "串刺しDPS:",
    "Culling DPS": "間引きDPS",
    "Culling DPS:": "間引きDPS:",
    "Caustic Ground DPS": "腐食地形DPS",
    "Caustic Ground DPS:": "腐食地形DPS:",
    "Corrupting Blood DPS": "汚染血液DPS",
    "Corrupting Blood DPS:": "汚染血液DPS:",
    "Mirage Caustic Ground DPS": "ミラージュ腐食地形DPS",
    "Mirage Caustic Ground DPS:": "ミラージュ腐食地形DPS:",
    "Reservation DPS": "予約DPS",
    "Reservation DPS:": "予約DPS:",
    "Dmg. of all Bleeds": "全出血ダメージ",
    "Dmg. of all Bleeds:": "全出血ダメージ:",
    "Dmg. of all Ignites": "全発火ダメージ",
    "Dmg. of all Ignites:": "全発火ダメージ:",
    "Dmg. of all Poisons": "全毒ダメージ",
    "Dmg. of all Poisons:": "全毒ダメージ:",
    "Dmg. Mit. Regen": "ダメ軽減自動回復",
    "Dmg. Mit. Regen:": "ダメ軽減自動回復:",
    "Debuff Dur. Mult.": "デバフ持続倍率",
    "Debuff Dur. Mult.:": "デバフ持続倍率:",

    # 時間関連
    "Channel Time": "チャネル時間",
    "Channel Time:": "チャネル時間:",
    "Channel time": "チャネル時間",
    "Channel time:": "チャネル時間:",
    "Cast Time": "詠唱時間",
    "Cast Time:": "詠唱時間:",
    "Detonation Time": "起爆時間",
    "Detonation Time:": "起爆時間:",
    "Reload Time": "リロード時間",
    "Reload Time:": "リロード時間:",
    "Channeling for # seconds:": "Nチャネリング秒数:",
    "Time spent stationary": "静止していた時間",
    "Time spent stationary:": "静止していた時間:",
    "Time to Gain Max Seals": "最大シール獲得までの時間",
    "Time to Gain Max Seals:": "最大シール獲得までの時間:",
    "Seal Gain Frequency": "シール獲得頻度",
    "Seal Gain Frequency:": "シール獲得頻度:",
    "Seal Gain Rate": "シール獲得レート",
    "Seal Gain Rate:": "シール獲得レート:",
    "Uptime": "稼働時間",
    "Uptime:": "稼働時間:",
    "Reserve Uptime": "予約稼働時間",
    "Reserve Uptime:": "予約稼働時間:",
    "Secondary Uptime": "二次稼働時間",
    "Secondary Uptime:": "二次稼働時間:",
    "Tertiary Uptime": "三次稼働時間",
    "Tertiary Uptime:": "三次稼働時間:",
    "Stored Uses": "蓄積使用回数",
    "Stored Uses:": "蓄積使用回数:",

    # 投射物・連鎖関連
    "Bolt Count": "ボルト数",
    "Bolt Count:": "ボルト数:",
    "Eff. Bolt Count": "実効ボルト数",
    "Eff. Bolt Count:": "実効ボルト数:",
    "Eff. Source Rate": "実効ソースレート",
    "Eff. Source Rate:": "実効ソースレート:",
    "Repeat Count": "反復数",
    "Repeat Count:": "反復数:",
    "Split Count": "分裂数",
    "Split Count:": "分裂数:",
    "Sources": "ソース",
    "Sources:": "ソース:",
    "Source rate for Intuitive Link": "Intuitive Linkのソースレート",
    "Source rate for Intuitive Link:": "Intuitive Linkのソースレート:",

    # 範囲・距離
    "AoE Radius": "範囲半径",
    "AoE Radius:": "範囲半径:",
    "Radius": "半径",
    "Radius:": "半径:",
    "Secondary Radius": "二次半径",
    "Secondary Radius:": "二次半径:",
    "Tertiary Radius": "三次半径",
    "Tertiary Radius:": "三次半径:",
    "Attachment Range": "接続範囲",
    "Attachment Range:": "接続範囲:",
    "Presence Radius": "プレゼンス半径",
    "Presence Radius:": "プレゼンス半径:",
    "Knockback Dist.": "ノックバック距離",
    "Knockback Dist.:": "ノックバック距離:",
    "MH K.B. Dist.": "MH ノックバック距離",
    "MH K.B. Dist.:": "MH ノックバック距離:",
    "OH K.B. Dist.": "OH ノックバック距離",
    "OH K.B. Dist.:": "OH ノックバック距離:",
    "OH Att. per second": "OH 毎秒攻撃",
    "OH Att. per second:": "OH 毎秒攻撃:",
    "Firing Rate": "発射レート",
    "Firing Rate:": "発射レート:",
    "Wave Pulse Rate": "波動レート",
    "Wave Pulse Rate:": "波動レート:",

    # ES詳細
    "ES Cost": "ESコスト",
    "ES Cost:": "ESコスト:",
    "ES Cost per second": "毎秒ESコスト",
    "ES Cost per second:": "毎秒ESコスト:",
    "ES Regen": "ES自動回復",
    "ES Regen:": "ES自動回復:",
    "ES Gain Rate": "ES獲得レート",
    "ES Gain Rate:": "ES獲得レート:",
    "ES Gain on Kill": "キル時ES獲得",
    "ES Gain on Kill:": "キル時ES獲得:",
    "ES Leech Rate": "ES吸収レート",
    "ES Leech Rate:": "ES吸収レート:",
    "ES Leech Cap": "ES吸収上限",
    "ES Leech Cap:": "ES吸収上限:",
    "ES on Suppression": "軽減時ES獲得",
    "ES on Suppression:": "軽減時ES獲得:",
    "ES per second": "毎秒ES",
    "ES per second:": "毎秒ES:",
    "ES % per second": "毎秒ES%",
    "ES % per second:": "毎秒ES%:",
    "ES Bypass %": "ES迂回%",
    "ES Bypass %:": "ES迂回%:",
    "Recoverable ES": "回復可能ES",
    "Recoverable ES:": "回復可能ES:",
    "Net Avg.": "正味平均",
    "Net Avg.:": "正味平均:",
    "Net Max.": "正味最大",
    "Net Max.:": "正味最大:",

    # 回収系
    "Recoup Avg.": "回収平均",
    "Recoup Avg.:": "回収平均:",
    "Recoup Max.": "回収最大",
    "Recoup Max.:": "回収最大:",
    "Phys Recoup": "物理回収",
    "Phys Recoup:": "物理回収:",
    "Ele Recoup": "属性回収",
    "Ele Recoup:": "属性回収:",
    "Light Recoup": "雷回収",
    "Light Recoup:": "雷回収:",
    "Faster Recoup": "高速回収",
    "Faster Recoup:": "高速回収:",
    "FasterRecoup": "高速回収",
    "FasterRecoup:": "高速回収:",
    "Reflect taken": "反射被害",
    "Reflect taken:": "反射被害:",

    # 回避率類
    "Bleed Avoid Ch.": "出血回避率",
    "Bleed Avoid Ch.:": "出血回避率:",
    "Blind Avoid Ch.": "盲目回避率",
    "Blind Avoid Ch.:": "盲目回避率:",
    "Chill Avoid Ch.": "冷却回避率",
    "Chill Avoid Ch.:": "冷却回避率:",
    "Freeze Avoid Ch.": "凍結回避率",
    "Freeze Avoid Ch.:": "凍結回避率:",
    "Ignite Avoid Ch.": "発火回避率",
    "Ignite Avoid Ch.:": "発火回避率:",
    "Impale Avoid Ch.": "串刺し回避率",
    "Impale Avoid Ch.:": "串刺し回避率:",
    "Interrupt Avoid Ch.": "妨害回避率",
    "Interrupt Avoid Ch.:": "妨害回避率:",
    "Poison Avoid Ch.": "毒回避率",
    "Poison Avoid Ch.:": "毒回避率:",
    "Sap Avoid Ch.": "弱体回避率",
    "Sap Avoid Ch.:": "弱体回避率:",
    "Scorch Avoid Ch.": "灼熱回避率",
    "Scorch Avoid Ch.:": "灼熱回避率:",
    "Shock Avoid Ch.": "感電回避率",
    "Shock Avoid Ch.:": "感電回避率:",
    "Silence Avoid Ch.": "沈黙回避率",
    "Silence Avoid Ch.:": "沈黙回避率:",
    "Avoid All Dmg Ch.": "全ダメ回避率",
    "Avoid All Dmg Ch.:": "全ダメ回避率:",
    "Avoid Proj Ch.": "投射物回避率",
    "Avoid Proj Ch.:": "投射物回避率:",
    "Suppression Ch.": "軽減率",
    "Suppression Ch.:": "軽減率:",
    "Melee Evade Ch.": "近接回避率",
    "Melee Evade Ch.:": "近接回避率:",
    "Proj. Evade Ch.": "投射物回避率",
    "Proj. Evade Ch.:": "投射物回避率:",

    # 免疫
    "Hinder Immune": "妨害免疫",
    "Hinder Immune:": "妨害免疫:",
    "Maim Immune": "切傷免疫",
    "Maim Immune:": "切傷免疫:",
    "Knockback Immune": "ノックバック免疫",
    "Knockback Immune:": "ノックバック免疫:",
    "Corr Blood Immune": "汚染血液免疫",
    "Corr Blood Immune:": "汚染血液免疫:",

    # 状態異常設定
    "Configured Chill": "設定済み冷却",
    "Configured Chill:": "設定済み冷却:",
    "Configured Sap": "設定済み弱体",
    "Configured Sap:": "設定済み弱体:",
    "Configured Scorch": "設定済み灼熱",
    "Configured Scorch:": "設定済み灼熱:",
    "Configured Shock": "設定済み感電",
    "Configured Shock:": "設定済み感電:",
    "Guaranteed Chills": "確定冷却",
    "Guaranteed Chills:": "確定冷却:",
    "Guaranteed Saps": "確定弱体",
    "Guaranteed Saps:": "確定弱体:",
    "Guaranteed Scorches": "確定灼熱",
    "Guaranteed Scorches:": "確定灼熱:",
    "Guaranteed Shocks": "確定感電",
    "Guaranteed Shocks:": "確定感電:",
    "Pin Buildup": "拘束蓄積",
    "Pin Buildup:": "拘束蓄積:",
    "Freeze Buildup": "凍結蓄積",
    "Freeze Buildup:": "凍結蓄積:",
    "Electrocute Buildup": "感電蓄積",
    "Electrocute Buildup:": "感電蓄積:",

    # その他ステータス
    "Defences from Shield": "盾からの防御",
    "Defences from Shield:": "盾からの防御:",
    "Bypass CD?": "クールダウン迂回?",
    "Bypass CD?:": "クールダウン迂回?:",
    "Conversions": "変換",
    "Conversions:": "変換:",
    "Leech Conversion": "吸収変換",
    "Leech Conversion:": "吸収変換:",
    "Mind over Matter %": "MoM %",
    "Mind over Matter %:": "MoM %:",
    "Tvalue Override (ms)": "T値上書き (ms)",
    "Tvalue Override (ms):": "T値上書き (ms):",
    "PvP Tvalue override (ms):": "PvP T値上書き (ms):",
    "CWDT Threshold": "CWDT閾値",
    "CWDT Threshold:": "CWDT閾値:",
    "Corpse Level": "死体レベル",
    "Corpse Level:": "死体レベル:",
    "IIQ for Normal Mobs": "ノーマル敵IIQ",
    "IIQ for Normal Mobs:": "ノーマル敵IIQ:",
    "IIR for Magic Mobs": "マジック敵IIR",
    "IIR for Magic Mobs:": "マジック敵IIR:",
    "Sustainable Trauma": "持続可能トラウマ",
    "Sustainable Trauma:": "持続可能トラウマ:",
    "Devotion": "献身",
    "Devotion:": "献身:",
    "Tribute": "貢物",
    "Tribute:": "貢物:",
    "Charm Limit": "チャーム上限",
    "Charm Limit:": "チャーム上限:",
    "Mark Limit": "マーク上限",
    "Mark Limit:": "マーク上限:",
    "Max Sust. Fuses": "最大持続ヒューズ",
    "Max Sust. Fuses:": "最大持続ヒューズ:",
    "Anc. Empowerment": "古代強化",
    "Anc. Empowerment:": "古代強化:",
    "AncestralEmpower+": "古代強化+",
    "AncestralEmpower+:": "古代強化+:",
    "Empowered Stats": "強化ステータス",
    "Empowered Stats:": "強化ステータス:",
    "Highest damage type Override:": "最大ダメージタイプの上書き:",
    "Highest damage type Override": "最大ダメージタイプの上書き",
    "Item Quantity": "アイテム数量",
    "Item Quantity:": "アイテム数量:",
    "Item Rarity": "アイテムレアリティ",
    "Item Rarity:": "アイテムレアリティ:",
    "Taken As": "受けたダメージタイプ",
    "Taken As:": "受けたダメージタイプ:",
    "Taken As Mod:": "ダメージタイプ補正:",
    "EHP calc unlucky:": "EHP計算 不運モード:",
    "Ignore Jewel Limits:": "ジュエル上限を無視:",
    "Small Explosions": "小爆発",
    "Small Explosions:": "小爆発:",
    "Explosions /s": "爆発/秒",
    "Explosions /s:": "爆発/秒:",
    "Terrain Chain": "地形連鎖",
    "Terrain Chain:": "地形連鎖:",
    "No Ammo Consume": "弾薬消費なし",
    "No Ammo Consume:": "弾薬消費なし:",
    "Perfect Timing": "完璧なタイミング",
    "Perfect Timing:": "完璧なタイミング:",
    "Fist of War": "戦の拳",
    "Fist of War:": "戦の拳:",
    "Last 25% of attached duration?": "付属持続時間の最後の25%?",
    "Last 50% of attached duration?": "付属持続時間の最後の50%?",
    "Last 25% of attached duration?:": "付属持続時間の最後の25%?:",
    "Last 50% of attached duration?:": "付属持続時間の最後の50%?:",
}


def translate_term(text: str) -> str:
    """テキスト中の単語を辞書置換 (長い key 優先)"""
    for key in sorted(TERMS.keys(), key=len, reverse=True):
        text = text.replace(key, TERMS[key])
    return text


def translate_label(label: str) -> str | None:
    """ラベルを訳す。EXACT 優先、なければパターンマッチ。"""
    if label in EXACT:
        return EXACT[label]

    # 色エスケープなど特殊文字を含む場合はパターンマッチ後で
    translated = translate_term(label)

    # 各種パターン
    patterns = [
        (r"^Are you (.+)\?$", "あなたは{0}ですか？"),
        (r"^Do you have (.+)\?$", "{0}を持っていますか？"),
        (r"^Do you use (.+)\?$", "{0}を使用しますか？"),
        (r"^Do your (.+)\?$", "あなたの{0}しますか？"),
        (r"^Do you (.+)\?$", "{0}しますか？"),
        (r"^Have you been (.+) Recently\?$", "最近{0}しましたか？"),
        (r"^Have you (.+) in the (?:past|last) (.+)\?$", "過去{1}で{0}しましたか？"),
        (r"^Have you (.+) [Rr]ecently\?$", "最近{0}しましたか？"),
        (r"^Have you (.+)\?$", "{0}しましたか？"),
        (r"^Have your (.+)\?$", "あなたの{0}しましたか？"),
        (r"^Is the enemy (.+)\?$", "敵は{0}ですか？"),
        (r"^Is enemy (.+)\?$", "敵は{0}ですか？"),
        (r"^Is (.+) active\?$", "{0}は有効ですか？"),
        (r"^Is (.+)\?$", "{0}ですか？"),
        (r"^Has (.+) consumed (.+)\?$", "{0}は{1}を消費しましたか？"),
        (r"^Did you (.+) yourself\?$", "自分に{0}しましたか？"),
        (r"^Did you (.+)\?$", "{0}しましたか？"),
        (r"^How many (.+)\?$", "いくつの{0}？"),
        (r"^Summoned (.+) in past (\d+) Seconds\?$", "過去{1}秒以内に{0}を召喚しましたか？"),
        (r"^Consumed (.+)\?$", "{0}を消費しましたか？"),
        (r"^Consumed (.+)$", "{0}を消費"),
        (r"^# of (.+) \(if not maximum\):$", "{0}の数 (最大でない場合):"),
        (r"^# of (.+) \(if not average\):$", "{0}の数 (平均でない場合):"),
        (r"^# of (.+):$", "{0}の数:"),
        (r"^# (.+)$", "{0}の数"),
        (r"^% (.+):$", "{0}の%:"),
        (r"^(.+) past (.+)\?$", "過去{1}で{0}？"),
        (r"^(.+) recently\?$", "最近{0}？"),
        (r"^Enable (.+)$", "{0}を有効化"),
        (r"^Disable (.+)$", "{0}を無効化"),
        (r"^(.+) [Mm]ode:$", "{0}モード:"),
        (r"^Last (\d+)% of attached duration\?$", "付属持続時間の最後の{0}%？"),
    ]

    for pat, fmt in patterns:
        m = re.match(pat, label)
        if m:
            groups = [translate_term(g) for g in m.groups()]
            return fmt.format(*groups)

    if translated != label:
        return translated
    return None


def extract_labels(file_paths: list[Path]) -> set[str]:
    """ソースファイルから label = "..." を全抽出。

    Lua のエスケープ済み引用符 (\\") を含む文字列も正しくキャプチャする。
    """
    # 引用符内: 非引用符・非バックスラッシュ 1文字 もしくは \\ + 任意1文字 の繰り返し
    label_re = re.compile(r'label = "((?:[^"\\]|\\.)*)"')

    labels: set[str] = set()
    for p in file_paths:
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        for m in label_re.findall(text):
            # Lua のエスケープを解除して実際の文字列を取得
            unescaped = m.replace(r"\"", '"').replace(r"\\", "\\")
            labels.add(unescaped)
            if not unescaped.endswith(":"):
                labels.add(unescaped + ":")
        # ButtonControl / LabelControl の文字列リテラル引数
        for m in re.findall(
            r'new\("(?:ButtonControl|LabelControl)"[^"]*,\s*"((?:[^"\\]|\\.)*)"',
            text,
        ):
            unescaped = m.replace(r"\"", '"').replace(r"\\", "\\")
            # 過剰抽出を避けるため、それっぽい UI 文字列だけ
            if re.match(r"^[A-Z][^\"]*[a-zA-Z?:]$", unescaped):
                labels.add(unescaped)
    return labels


def main() -> None:
    project_root = Path(__file__).parent.parent.parent
    file_paths = [project_root / f for f in SOURCE_FILES]
    labels = extract_labels(file_paths)
    print(f"抽出ラベル数: {len(labels)}")

    out_lines = [
        "",
        "\t-- ============================================================",
        "\t-- UI自動翻訳 (translate_ui.py で生成)",
        "\t-- 対象: CalcsTab, CalcSections, ItemsTab, SkillsTab, TreeTab,",
        "\t--       ConfigTab, ConfigOptions, BuildDisplayStats, Build, ...",
        "\t-- ============================================================",
    ]
    translated = 0
    untranslated: list[str] = []
    seen: set[str] = set()
    for label in sorted(labels):
        if label in seen:
            continue
        seen.add(label)
        ja = translate_label(label)
        if ja is None or ja == label:
            untranslated.append(label)
            continue
        key = label.replace("\\", "\\\\").replace('"', '\\"')
        val = ja.replace("\\", "\\\\").replace('"', '\\"')
        out_lines.append(f'\t["{key}"] = "{val}",')
        translated += 1

    out_path = Path(__file__).parent / "ui_translations.lua"
    out_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

    untrans_path = Path(__file__).parent / "ui_untranslated.txt"
    untrans_path.write_text("\n".join(untranslated) + "\n", encoding="utf-8")

    print(f"翻訳済み:   {translated}")
    print(f"未翻訳:     {len(untranslated)}")
    print(f"出力:       {out_path}")
    print(f"未翻訳一覧: {untrans_path}")

    # 出力ファイルが実 Lua パーサで読み込めるか検証
    try:
        import lupa  # type: ignore
        lua = lupa.LuaRuntime()
        wrapped = "local t = {" + "\n".join(out_lines) + "}\nreturn t"
        try:
            lua.execute(wrapped)
            print("Lua 構文検証: OK")
        except lupa.LuaError as e:
            print(f"Lua 構文検証: NG ({e})")
    except ImportError:
        print("(lupa 未インストール - Lua 構文検証スキップ)")


if __name__ == "__main__":
    main()
